apiVersion: apps/v1
kind: Deployment
metadata:
  name: bff
spec:
  replicas: 1
  selector:
    matchLabels:
      app: bff
  template:
    metadata:
      labels:
        app: bff
    spec:
      containers:
        - name: bff
          image: cyldecryo/bff:3c3fb369212f01b7553599e925e19f24a4184235
          ports:
            - containerPort: 5000
