apiVersion: apps/v1
kind: Deployment
metadata:
  name: bff
spec:
  replicas: 1
  selector:
    matchLabels:
      app: bff
  template:
    metadata:
      labels:
        app: bff
    spec:
      containers:
        - name: bff
          image: cyldecryo/bff:cc2721f0f4676eb001a678c735091cf38575de40
          ports:
            - containerPort: 5000
