apiVersion: apps/v1
kind: Deployment
metadata:
  name: bff
spec:
  replicas: 1
  selector:
    matchLabels:
      app: bff
  template:
    metadata:
      labels:
        app: bff
    spec:
      containers:
        - name: bff
          image: cyldecryo/bff:24c59c47e814392aebe92074801188315d5b404e
          ports:
            - containerPort: 5000
