apiVersion: apps/v1
kind: Deployment
metadata:
  name: bff
spec:
  replicas: 1
  selector:
    matchLabels:
      app: bff
  template:
    metadata:
      labels:
        app: bff
    spec:
      containers:
        - name: bff
          image: cyldecryo/bff:90871dd48ea7c0d836faa928a7a63aa56c37161b
          ports:
            - containerPort: 5000
