apiVersion: apps/v1
kind: Deployment
metadata:
  name: bff
spec:
  replicas: 1
  selector:
    matchLabels:
      app: bff
  template:
    metadata:
      labels:
        app: bff
    spec:
      containers:
      - name: bff
        image: cyldecryo/bff:latest
        ports:
        - containerPort: 5000
---
apiVersion: v1
kind: Service
metadata:
  name: bff-service
spec:
  type: NodePort  
  selector:
    app: bff
  ports:
    - protocol: TCP
      port: 5000
      targetPort: 5000
      nodePort: 30002  
