apiVersion: apps/v1
kind: Deployment
metadata:
  name: bff
spec:
  replicas: 1
  selector:
    matchLabels:
      app: bff
  template:
    metadata:
      labels:
        app: bff
    spec:
      containers:
        - name: bff
          image: cyldecryo/bff:889320f9812d60da7545541a3e5ed1cf57e2d0bc
          ports:
            - containerPort: 8081
