apiVersion: apps/v1
kind: Deployment
metadata:
  name: frontend
spec:
  replicas: 1
  selector:
    matchLabels:
      app: frontend
  template:
    metadata:
      labels:
        app: frontend
    spec:
      containers:
        - name: frontend
          image: cyldecryo/front:6113076d2527722297c4a57957ec0307bbae5c50
          ports:
            - containerPort: 8080
