apiVersion: apps/v1
kind: Deployment
metadata:
  name: frontend
spec:
  replicas: 1
  selector:
    matchLabels:
      app: frontend
  template:
    metadata:
      labels:
        app: frontend
    spec:
      containers:
        - name: frontend
          image: cyldecryo/front:9c552bd7e0f6415fb026d65f09051cac4d124c1d
          ports:
            - containerPort: 8080
